name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: constants.env
          envkey_TEST: "test"
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /maccas-hot-bbq-sauce-frontend/
          customArgs: --dart-define=BACKEND_API_URL=${{ secrets.BACKEND_API_URL }},IS_SAMPLE=${{ secrets.IS_SAMPLE }},STOP_ID=${{ secrets.STOP_ID }}
